const Item = require('../src/item')
const assert = require('assert').strict

describe('integration test', function () {
  it('should be able to get the title', function () {
    const item = new Item('myItem')
    const title = item.getTitle()
    assert.strictEqual(title, 'myItem')
  })

  xit('should be able to get the id', function () {
    // Get id which was generated by id generator
  })

  xit('should be able to get the order', function () {
    // Get order which was assigned automically at creation
  })
})
